### PR TITLE
minor fix

### PR DESCRIPTION
**Pull request by haarperr**

### CODE REVIEW

**Comment by LiamMC534** [comment]
hey, is there an estimated time on fully fixed, cant wait for it thank you, also im struggling to find the line of code for keybinds is there something to look out for

**Comment by kristianse** [comment]
hi, im getting this error when i select my character, and then the loading screen just freezes. 
SCRIPT ERROR: @np-base/core/sv_characters.lua:215: ceil takes a number, integer, vector2, vector3, or vector4

local selectedCharacter = user:getCharacter(id)
	selectedCharacter.phone_number = math.ceil(selectedCharacter.phone_number)
	--print('selecting char')

isnt this right ?
thanks for help :)

**Comment by haarperr** [comment]
> hi, im getting this error when i select my character, and then the loading screen just freezes.
> SCRIPT ERROR: @np-base/core/sv_characters.lua:215: ceil takes a number, integer, vector2, vector3, or vector4
> 
> local selectedCharacter = user:getCharacter(id)
> selectedCharacter.phone_number = math.ceil(selectedCharacter.phone_number)
> --print('selecting char')
> 
> isnt this right ?
> thanks for help :)

it should be
selectedCharacter.phone_number = selectedCharacter.phone_number

**Comment by haarperr** [comment]
try this and lemme know

**Comment by kristianse** [comment]
that worked, thanks so much

**Pull request closed without merging**
